"""next change

Revision ID: 146619ebc5e6
Revises: 6eb32ce30a39
Create Date: 2025-11-15 12:57:43.144857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '146619ebc5e6'
down_revision: Union[str, Sequence[str], None] = '6eb32ce30a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('logs', sa.Column('level', sa.String(length=16), nullable=True))
    op.add_column('logs', sa.Column('message', sa.Text(), nullable=False))
    op.add_column('logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('logs', 'sermon_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_logs_log_id'), table_name='logs')
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.drop_constraint(op.f('logs_segment_id_fkey'), 'logs', type_='foreignkey')
    op.drop_column('logs', 'flag')
    op.drop_column('logs', 'event_time')
    op.drop_column('logs', 'session_id')
    op.drop_column('logs', 'segment_id')
    op.drop_column('logs', 'log_id')
    op.drop_column('logs', 'alignment_confidence')
    op.drop_column('logs', 'display_time_seconds')
    op.add_column('segments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('ix_segments_segment_order'), table_name='segments')
    op.drop_column('segments', 'last_reviewed_date')
    op.drop_column('segments', 'last_reviewed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('last_reviewed_by', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('segments', sa.Column('last_reviewed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_segments_segment_order'), 'segments', ['segment_order'], unique=False)
    op.drop_column('segments', 'created_at')
    op.add_column('logs', sa.Column('display_time_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('alignment_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('log_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('logs', sa.Column('segment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('session_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('event_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('logs', sa.Column('flag', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('logs_segment_id_fkey'), 'logs', 'segments', ['segment_id'], ['segment_id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.create_index(op.f('ix_logs_log_id'), 'logs', ['log_id'], unique=False)
    op.alter_column('logs', 'sermon_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('logs', 'created_at')
    op.drop_column('logs', 'message')
    op.drop_column('logs', 'level')
    op.drop_column('logs', 'id')
    # ### end Alembic commands ###
