"""Initial schema

Revision ID: 6eb32ce30a39
Revises: 
Create Date: 2025-11-07 08:31:13.008816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb32ce30a39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sermons',
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('speaker', sa.String(length=150), nullable=True),
    sa.Column('date_uploaded', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('sermon_id')
    )
    op.create_index(op.f('ix_sermons_sermon_id'), 'sermons', ['sermon_id'], unique=False)
    op.create_table('segments',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('segment_order', sa.Integer(), nullable=False),
    sa.Column('malay_text', sa.Text(), nullable=False),
    sa.Column('english_text', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_vetted', sa.Boolean(), nullable=True),
    sa.Column('last_reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('last_reviewed_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.sermon_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_id')
    )
    op.create_index(op.f('ix_segments_segment_id'), 'segments', ['segment_id'], unique=False)
    op.create_index(op.f('ix_segments_segment_order'), 'segments', ['segment_order'], unique=False)
    op.create_index(op.f('ix_segments_sermon_id'), 'segments', ['sermon_id'], unique=False)
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('alignment_confidence', sa.Float(), nullable=True),
    sa.Column('display_time_seconds', sa.Float(), nullable=True),
    sa.Column('flag', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.sermon_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_logs_log_id'), 'logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_logs_sermon_id'), 'logs', ['sermon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_sermon_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_log_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_segments_sermon_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_segment_order'), table_name='segments')
    op.drop_index(op.f('ix_segments_segment_id'), table_name='segments')
    op.drop_table('segments')
    op.drop_index(op.f('ix_sermons_sermon_id'), table_name='sermons')
    op.drop_table('sermons')
    # ### end Alembic commands ###
