"""Add analytics tables: live_sessions, live_session_logs, vetting_history, activity_log

Revision ID: b0d1d818e533
Revises: fbc64edbbfa7
Create Date: 2026-01-24 10:29:11.116597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0d1d818e533'
down_revision: Union[str, Sequence[str], None] = 'fbc64edbbfa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('total_segments_matched', sa.Integer(), nullable=True),
    sa.Column('total_segments_skipped', sa.Integer(), nullable=True),
    sa.Column('total_wrong_matches', sa.Integer(), nullable=True),
    sa.Column('total_manual_overrides', sa.Integer(), nullable=True),
    sa.Column('avg_match_score', sa.Float(), nullable=True),
    sa.Column('min_match_score', sa.Float(), nullable=True),
    sa.Column('max_match_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.sermon_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_sessions_started_at', 'live_sessions', ['started_at'], unique=False)
    op.create_index('idx_live_sessions_status', 'live_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_live_sessions_id'), 'live_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_live_sessions_sermon_id'), 'live_sessions', ['sermon_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_session_id'), 'live_sessions', ['session_id'], unique=True)
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('sermon_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.sermon_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_log_created_at', 'activity_log', ['created_at'], unique=False)
    op.create_index('idx_activity_log_event_type', 'activity_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_log_event_type'), 'activity_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_log_id'), 'activity_log', ['id'], unique=False)
    op.create_index(op.f('ix_activity_log_sermon_id'), 'activity_log', ['sermon_id'], unique=False)
    op.create_table('live_session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('spoken_text', sa.Text(), nullable=True),
    sa.Column('matched_segment_order', sa.Integer(), nullable=True),
    sa.Column('alignment_score', sa.Float(), nullable=True),
    sa.Column('threshold_used', sa.Float(), nullable=True),
    sa.Column('skipped_from_order', sa.Integer(), nullable=True),
    sa.Column('skipped_to_order', sa.Integer(), nullable=True),
    sa.Column('skipped_count', sa.Integer(), nullable=True),
    sa.Column('expected_segment_id', sa.Integer(), nullable=True),
    sa.Column('expected_segment_order', sa.Integer(), nullable=True),
    sa.Column('correction_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.sermon_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['live_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_live_session_logs_created_at', 'live_session_logs', ['created_at'], unique=False)
    op.create_index('idx_live_session_logs_event_type', 'live_session_logs', ['event_type'], unique=False)
    op.create_index('idx_live_session_logs_session_event', 'live_session_logs', ['session_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_live_session_logs_event_type'), 'live_session_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_live_session_logs_id'), 'live_session_logs', ['id'], unique=False)
    op.create_index(op.f('ix_live_session_logs_segment_id'), 'live_session_logs', ['segment_id'], unique=False)
    op.create_index(op.f('ix_live_session_logs_sermon_id'), 'live_session_logs', ['sermon_id'], unique=False)
    op.create_index(op.f('ix_live_session_logs_session_id'), 'live_session_logs', ['session_id'], unique=False)
    op.create_table('vetting_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('previous_english_text', sa.Text(), nullable=True),
    sa.Column('new_english_text', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.sermon_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vetting_history_action', 'vetting_history', ['action'], unique=False)
    op.create_index('idx_vetting_history_created_at', 'vetting_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_vetting_history_action'), 'vetting_history', ['action'], unique=False)
    op.create_index(op.f('ix_vetting_history_id'), 'vetting_history', ['id'], unique=False)
    op.create_index(op.f('ix_vetting_history_segment_id'), 'vetting_history', ['segment_id'], unique=False)
    op.create_index(op.f('ix_vetting_history_sermon_id'), 'vetting_history', ['sermon_id'], unique=False)
    op.add_column('segments', sa.Column('needs_revision', sa.Boolean(), nullable=True))
    op.add_column('segments', sa.Column('revision_notes', sa.Text(), nullable=True))
    op.add_column('segments', sa.Column('vetted_by', sa.String(length=150), nullable=True))
    op.add_column('segments', sa.Column('vetted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_segments_segment_order'), 'segments', ['segment_order'], unique=False)
    op.drop_column('segments', 'last_reviewed_by')
    op.drop_column('segments', 'last_reviewed_date')
    op.add_column('sermons', sa.Column('delivered_count', sa.Integer(), nullable=True))
    op.add_column('sermons', sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sermons', 'last_delivered_at')
    op.drop_column('sermons', 'delivered_count')
    op.add_column('segments', sa.Column('last_reviewed_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('segments', sa.Column('last_reviewed_by', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_segments_segment_order'), table_name='segments')
    op.drop_column('segments', 'vetted_at')
    op.drop_column('segments', 'vetted_by')
    op.drop_column('segments', 'revision_notes')
    op.drop_column('segments', 'needs_revision')
    op.drop_index(op.f('ix_vetting_history_sermon_id'), table_name='vetting_history')
    op.drop_index(op.f('ix_vetting_history_segment_id'), table_name='vetting_history')
    op.drop_index(op.f('ix_vetting_history_id'), table_name='vetting_history')
    op.drop_index(op.f('ix_vetting_history_action'), table_name='vetting_history')
    op.drop_index('idx_vetting_history_created_at', table_name='vetting_history')
    op.drop_index('idx_vetting_history_action', table_name='vetting_history')
    op.drop_table('vetting_history')
    op.drop_index(op.f('ix_live_session_logs_session_id'), table_name='live_session_logs')
    op.drop_index(op.f('ix_live_session_logs_sermon_id'), table_name='live_session_logs')
    op.drop_index(op.f('ix_live_session_logs_segment_id'), table_name='live_session_logs')
    op.drop_index(op.f('ix_live_session_logs_id'), table_name='live_session_logs')
    op.drop_index(op.f('ix_live_session_logs_event_type'), table_name='live_session_logs')
    op.drop_index('idx_live_session_logs_session_event', table_name='live_session_logs')
    op.drop_index('idx_live_session_logs_event_type', table_name='live_session_logs')
    op.drop_index('idx_live_session_logs_created_at', table_name='live_session_logs')
    op.drop_table('live_session_logs')
    op.drop_index(op.f('ix_activity_log_sermon_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_event_type'), table_name='activity_log')
    op.drop_index('idx_activity_log_event_type', table_name='activity_log')
    op.drop_index('idx_activity_log_created_at', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_live_sessions_session_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_sermon_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_id'), table_name='live_sessions')
    op.drop_index('idx_live_sessions_status', table_name='live_sessions')
    op.drop_index('idx_live_sessions_started_at', table_name='live_sessions')
    op.drop_table('live_sessions')
    # ### end Alembic commands ###
