"""add raw_text column to sermons

Revision ID: fbc64edbbfa7
Revises: 146619ebc5e6
Create Date: 2025-11-21 10:42:13.852650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc64edbbfa7'
down_revision: Union[str, Sequence[str], None] = '146619ebc5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sermons', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sermons', 'raw_text')
    # ### end Alembic commands ###
